/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submissaoCientifica;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import java.awt.Font;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import java.awt.CardLayout;
import java.awt.GridLayout;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author jessi
 */
public class SubCienGUI extends javax.swing.JFrame {
	private JTextField textField;
	private JTextField textField_2;
	private JTextField text_Res;
	private JTextField text_Titulo;
	private JTextField text_Inst;
	private JTextField text_Abs;

    /**
     * Creates new form SubCienGUI
     */
    public SubCienGUI() {
    	setTitle("Submiss\u00F5es");
    	getContentPane().setBackground(new Color(204, 204, 255));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JTabbedPane menu_Cien = new JTabbedPane(JTabbedPane.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setAutoCreateContainerGaps(true);
        layout.setAutoCreateGaps(true);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(menu_Cien, GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(menu_Cien, GroupLayout.PREFERRED_SIZE, 382, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(59, Short.MAX_VALUE))
        );
        
        JPanel consulta_Cientifica = new JPanel();
        menu_Cien.addTab("Consulta", null, consulta_Cientifica, null);
        consulta_Cientifica.setLayout(null);
        
        JLabel lblTitulo = new JLabel("Titulo:");
        lblTitulo.setFont(new Font("Tahoma", Font.PLAIN, 15));
        lblTitulo.setBounds(10, 58, 48, 14);
        consulta_Cientifica.add(lblTitulo);
        
        textField = new JTextField();
        textField.setBounds(61, 57, 276, 20);
        consulta_Cientifica.add(textField);
        textField.setColumns(10);
        
        JButton btnConsultar = new JButton("Consultar");
        btnConsultar.setBounds(140, 138, 89, 23);
        consulta_Cientifica.add(btnConsultar);
        
        JPanel cadastro_Cientifica = new JPanel();
        menu_Cien.addTab("Cadastro", null, cadastro_Cientifica, null);
        cadastro_Cientifica.setLayout(new GridLayout(1, 0, 0, 0));
        
        JTabbedPane tabbedPane_1 = new JTabbedPane(JTabbedPane.TOP);
        cadastro_Cientifica.add(tabbedPane_1);
        
        JPanel artigo = new JPanel();
        tabbedPane_1.addTab("Artigo", null, artigo, null);
        artigo.setLayout(null);
        
        JLabel lblTitulo_2 = new JLabel("Titulo");
        lblTitulo_2.setBounds(10, 25, 48, 14);
        artigo.add(lblTitulo_2);
        
        JLabel label_Sit = new JLabel("Situa\u00E7\u00E3o");
        label_Sit.setBounds(10, 62, 48, 14);
        artigo.add(label_Sit);
        
        JComboBox combo_Sit = new JComboBox();
        combo_Sit.setBounds(68, 58, 83, 22);
        artigo.add(combo_Sit);
        
        JLabel lblAutor = new JLabel("Autor");
        lblAutor.setBounds(10, 120, 48, 14);
        artigo.add(lblAutor);
        
        JList list_Aut = new JList();
        list_Aut.setBounds(68, 102, 247, 50);
        artigo.add(list_Aut);
        
        JLabel lblPalavrachave = new JLabel("Palavra-Chave");
        lblPalavrachave.setBounds(10, 207, 70, 14);
        artigo.add(lblPalavrachave);
        
        JList list_PalCha = new JList();
        list_PalCha.setBounds(90, 196, 225, 33);
        artigo.add(list_PalCha);
        
        JLabel lblResumo = new JLabel("Resumo");
        lblResumo.setBounds(10, 248, 48, 14);
        artigo.add(lblResumo);
        
        text_Res = new JTextField();
        text_Res.setBounds(68, 245, 247, 33);
        artigo.add(text_Res);
        text_Res.setColumns(10);
        
        JScrollPane scrollPane_1 = new JScrollPane();
        scrollPane_1.setViewportBorder(new BevelBorder(BevelBorder.LOWERED, Color.BLACK, Color.BLACK, Color.BLACK, Color.BLACK));
        scrollPane_1.setEnabled(false);
        scrollPane_1.setBounds(338, 322, -19, -319);
        artigo.add(scrollPane_1);
        
        text_Titulo = new JTextField();
        text_Titulo.setBounds(68, 22, 247, 20);
        artigo.add(text_Titulo);
        text_Titulo.setColumns(10);
        
        JLabel lblInstituio = new JLabel("Institui\u00E7\u00E3o");
        lblInstituio.setBounds(10, 165, 57, 14);
        artigo.add(lblInstituio);
        
        text_Inst = new JTextField();
        text_Inst.setBounds(68, 163, 247, 20);
        artigo.add(text_Inst);
        text_Inst.setColumns(10);
        
        JLabel lblAbstract = new JLabel("Abstract");
        lblAbstract.setBounds(10, 292, 48, 14);
        artigo.add(lblAbstract);
        
        text_Abs = new JTextField();
        text_Abs.setColumns(10);
        text_Abs.setBounds(68, 289, 247, 33);
        artigo.add(text_Abs);
        
        JPanel resumo = new JPanel();
        tabbedPane_1.addTab("Resumo", null, resumo, null);
        resumo.setLayout(null);
        
        JPanel relatorio = new JPanel();
        tabbedPane_1.addTab("Relatorio", null, relatorio, null);
        relatorio.setLayout(null);
        
        JPanel monografia = new JPanel();
        tabbedPane_1.addTab("Monografia", null, monografia, null);
        monografia.setLayout(null);
        
        JLabel lblTitulo_1 = new JLabel("Titulo:");
        lblTitulo_1.setBounds(10, 11, 48, 14);
        monografia.add(lblTitulo_1);
        
        textField_2 = new JTextField();
        textField_2.setBounds(68, 8, 251, 20);
        monografia.add(textField_2);
        textField_2.setColumns(10);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubCienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubCienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubCienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubCienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubCienGUI().setVisible(true);
            }
        });
    }
}
